---
- name: check if ansible is not to old
  hosts: localhost
  tags:
   - default
  roles:
    - version
  gather_facts: no

- hosts: all
  roles:
    - { role: ntp, tags: [defaults,base,ntp]}
    - { role: users, tags: [default,base,users]}
    - { role: ranger, tags: [defaults,base,ranger]}
    - { role: packages, tags: [defaults,base,packages]}
    - { role: bat, tags: [defaults,base,bat], become: true}
    - { role: dotfiles, tags: [defaults,base,dotfiles]}
    - { role: ssh-auth, tags: [defaults,base,ssh,ssh-auth]}
    - { role: sshd, tags: [default,base,ssh,sshd]}
- hosts: webserver
  roles:
    - { role: letsencrypt, tags: [web,letsencrypt], become: true}
    - { role: nginx, tags: [web,nginx]}
